name: Generate Documentation
on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  docs:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-20.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Checkout docs branch and merge main
        run: |
          git config user.name coveobot
          git config user.email coveobot@coveo.com
          git checkout docs
          git merge main

      - name: Generate the docs
        run: |
          rm -rf ./docs/
          doxygen Doxyfile

      - name: Push the docs
        run: |
          git add docs/
          git commit -m "Update documentation" || status=$?
          git push origin docs

