name: Tests

on:
  push: {}

jobs:
  unit:
    # TODO: Add different compilers to the matrix.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install apt dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y clang build-essential libssl-dev curl ninja-build libboost-all-dev libgtest-dev

      - name: Build Tests
        run: |
          mkdir -p build/
          cd build/
          cmake -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .

      - name: Run Tests
        run: |
          ./build/tests/cachemere_tests
